### ISSUE TITLE
Training not stable

### ISSUE THREAD

**Issue by alwynmathew** [alwynmathew/monodepth-pytorch#1]
Training not as stable as [original tensorflow implementation](https://github.com/mrharicot/monodepth). Main suspect could be the bilinear sampler.

**Comment by alwynmathew** [comment]
Fixed with ec9705617eea4d5d2d5e2b6b99a36849f2c838d8

**Comment by C2H5OHlife** [comment]
Hello, did you really solve this problem by replacing grid_sample with a hand-made sample function? Do you know why grid_sample doesn't work well?
