### ISSUE TITLE
about training is not stable

### ISSUE THREAD

**Issue by xiaohedu** [alwynmathew/monodepth-pytorch#2]
Hi , please ask you have you solved it about unstable training ? I am using our data for training monodepth, 
      the model performance get worse .
      I want ask  is it required high quality pictures and a lot of pictures for monodepth training ?
      I only have  4000 RGB  images .

**Comment by alwynmathew** [comment]
4000 images seem very few compared to 28,000 left and right image pairs in KITTI which we used for training.

**Comment by Sudonuma** [comment]
Hello, 
since they are asking here about the training instability, I would like to ask if the problem is really solved, 
I am using the same network with the same parameters and training images but still I have those weird results you noted on your issues.
